version: '3.9'

services:
  dash:
    command: python3 app.py
    image: ait-ml-assignment3-dash:2025
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80